# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  buildConfiguration: 'Release'
  artifactStagingDirectory: 'bin/publish'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    
- task: DotNetCoreCLI@2
  inputs:
    command: publish 
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) -r linux-x64 /p:PublishSingleFile=true --output $(artifactStagingDirectory)/VulkanRen-linux'
    zipAfterPublish: false

- task: CopyFiles@2
  inputs:
    SourceFolder: res
    TargetFolder: $(artifactStagingDirectory)/VulkanRen-linux/res/

- task: CopyFiles@2
  inputs:
    SourceFolder: shaders
    TargetFolder: $(artifactStagingDirectory)/VulkanRen-linux/shaders/

- task: DotNetCoreCLI@2
  inputs:
    command: publish 
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) -r win-x64 /p:PublishSingleFile=true --output $(artifactStagingDirectory)/VulkanRen-win'
    zipAfterPublish: false

- task: CopyFiles@2
  inputs:
    SourceFolder: res
    TargetFolder: $(artifactStagingDirectory)/VulkanRen-win/res/

- task: CopyFiles@2
  inputs:
    SourceFolder: shaders
    TargetFolder: $(artifactStagingDirectory)/VulkanRen-win/shaders/

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(artifactStagingDirectory)' 
    artifactName: 'VulkanRen'




